# 01 — OMI Data Exploration

## 1. Setup

In [1]:
import pandas as pd
import numpy as np
from pathlib import Path
import matplotlib.pyplot as plt

## 2. Load data

In [2]:
# =============================================================================
# CONFIGURATION
# =============================================================================

CWD = Path.cwd()
PROJECT_ROOT = CWD.parent

INPUT_FOLDER = PROJECT_ROOT / "data" / "raw" / "omi"

FILE_PREVIEW = INPUT_FOLDER / "omi_quotations_2018_S1.csv"


# =============================================================================
# LOAD DATA
# =============================================================================

df_omi_example = pd.read_csv(
    FILE_PREVIEW,
    sep=";",
)

df_omi_example.head()

,Area_territoriale,Regione,Prov,Comune_ISTAT,Comune_cat,Sez,Comune_amm,Comune_descrizione,Fascia,Zona,...,Descr_Tipologia,Stato,Stato_prev,Compr_min,Compr_max,Sup_NL_compr,Loc_min,Loc_max,Sup_NL_loc,Unnamed: 21
0,NORD-OVEST,PIEMONTE,AL,1006003.0,A2AA,,A182,ALESSANDRIA,B,B1,...,Abitazioni civili,NORMALE,P,720.0,910.0,L,4,"5,1",L,NaN
1,NORD-OVEST,PIEMONTE,AL,1006003.0,A2AA,,A182,ALESSANDRIA,B,B1,...,Box,NORMALE,P,1100.0,1600.0,L,"4,4","6,2",L,NaN
2,NORD-OVEST,PIEMONTE,AL,1006003.0,A2AA,,A182,ALESSANDRIA,B,B1,...,Posti auto coperti,NORMALE,P,700.0,1000.0,L,"2,7","3,8",L,NaN
3,NORD-OVEST,PIEMONTE,AL,1006003.0,A2AA,,A182,ALESSANDRIA,B,B1,...,Posti auto scoperti,NORMALE,P,600.0,800.0,L,"2,5","3,3",L,NaN
4,NORD-OVEST,PIEMONTE,AL,1006003.0,A2AA,,A182,ALESSANDRIA,B,B1,...,Magazzini,NORMALE,P,900.0,1300.0,L,"4,8","5,7",L,NaN

In [3]:
file_names = [
    file for file in INPUT_FOLDER.iterdir()
    if file.suffix == ".csv"
]


def extract_data_from_file_name(file_name):
    parts = file_name.stem.split("_")

    year = int(parts[2])
    semester = parts[3]

    if semester == "S1":
        month = 6
    elif semester == "S2":
        month = 12
    else:
        raise ValueError(f"Invalid semester: {semester}")

    return pd.Timestamp(
        year=year,
        month=month,
        day=1,
    ) + pd.offsets.MonthEnd(0)


def import_csv_files_with_reference_data(file_names):
    dataframes = []

    for file_name in file_names:
        df = pd.read_csv(
            file_name,
            sep=";",
        )

        df["reference_date"] = extract_data_from_file_name(file_name)

        dataframes.append(df)

    return pd.concat(
        dataframes,
        ignore_index=True,
    )

df_omi = import_csv_files_with_reference_data(file_names)

df_omi.head()

,Area_territoriale,Regione,Prov,Comune_ISTAT,Comune_cat,Sez,Comune_amm,Comune_descrizione,Fascia,Zona,...,Stato,Stato_prev,Compr_min,Compr_max,Sup_NL_compr,Loc_min,Loc_max,Sup_NL_loc,Unnamed: 21,reference_date
0,NORD-OVEST,PIEMONTE,AL,1006003.0,A2AA,,A182,ALESSANDRIA,B,B1,...,NORMALE,P,720.0,910.0,L,4,"5,1",L,NaN,2018-06-30
1,NORD-OVEST,PIEMONTE,AL,1006003.0,A2AA,,A182,ALESSANDRIA,B,B1,...,NORMALE,P,1100.0,1600.0,L,"4,4","6,2",L,NaN,2018-06-30
2,NORD-OVEST,PIEMONTE,AL,1006003.0,A2AA,,A182,ALESSANDRIA,B,B1,...,NORMALE,P,700.0,1000.0,L,"2,7","3,8",L,NaN,2018-06-30
3,NORD-OVEST,PIEMONTE,AL,1006003.0,A2AA,,A182,ALESSANDRIA,B,B1,...,NORMALE,P,600.0,800.0,L,"2,5","3,3",L,NaN,2018-06-30
4,NORD-OVEST,PIEMONTE,AL,1006003.0,A2AA,,A182,ALESSANDRIA,B,B1,...,NORMALE,P,900.0,1300.0,L,"4,8","5,7",L,NaN,2018-06-30

## 3. Dataset overview

## 4. Temporal coverage

## 5. Geographic coverage

## 6. Property categories

## 7. OMI quotations

## 8. Transaction volumes

## 9. Missing values

## 10. Duplicates

## 11. Data consistency

## 12. Initial descriptive statistics

## 13. First visualizations

## 14. Conclusions